# Site settings
title: Candace Y.'s Blog
SEOTitle: 易渔的博客|Candace Y.'s Blog|中英翻译|中英笔译|翻译|学术翻译|商务翻译|论文翻译|文学翻译|中英互译|Experienced Chinese Translator
header-img: img/post-bg-desk.jpg
email: yyx0015@gmail.com
description: "Every failure is leading towards success."
keyword: "易渔, Candace Y.'s Blog, 易渔的博客, Candace Y., 译者, 翻译, Chinese Translator, Translation"
url: "https://candaceycan.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/CandaceYcan/CandaceYcan.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一枚奋进的翻译 | 信条：Better late than never!"
sidebar-avatar: /img/About-Candace.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
# github_username:    CandaceYcan
jianshu_username:   3e3589c59c3f
douban_username:   somewise
#twitter_username:   somewise007




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 18
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: CandaceYcan 

#intensedebate修改成你自己的
intensedebate_identifier: 797e6926f0b277c7a215c2ff397bfe2c
 

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e8f27f83cc424e35fdd3                            #生成的clientID
  clientSecret: f1dee785536ee5feb35b2bd05f341dd526949a4f    #生成的clientSecret
  repo: CandaceYcan.github.io    #仓库名称
  owner: CandaceYcan    #github用户名
  admin: CandaceYcan
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
baidu-analysis: aa143afd521f44de6e6f664296a4eafc

# Google Analytics
ga_track_id:             # Format: UA-xxxxxx-xx
ga_domain:               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "豆瓣·易渔",
        href: "https://www.douban.com/people/somewise/"
    },{
        title: "简书·易渔",
        href: "https://www.jianshu.com/u/3e3589c59c3f"
    }
]

#添加分类步骤：
#1：在_config.yml links1及blog_中添加对应内容
#2：在_includes里面header.html中添加对应内容
#3：在根目录blog文件中创建对应内容


links1:
  - name:         所有
    url:          /
    type:         recent
    external:     false
  - name:         日记
    url:          /blog/diaries
    type:         diaries
    external:     false
  - name:         Translations
    url:          /blog/translations
    type:         translations
    external:     false
  - name:         Learning records
    url:          /blog/learningrecords
    type:         learningrecords
    external:     false
  - name:         Notes on translations
    url:          /blog/notesontranslations
    type:         notesontranslations
    external:     false
  - name:         Novel
    url:          /blog/novel
    type:         novel
    external:     false
  - name:         Other
    url:          /blog/other
    type:         other
    external:     false
  - name:        
    url:          
    type:         
    external:     
  
blog_1:    recent
blog_2:    diaries
blog_3:    translations
blog_4:    learningrecords
blog_5:    notesontranslations
blog_6:    novel
blog_7:    other
blog_8:    
blog_9:    
blog_10:   
blog_11:   
blog_12:   
blog_13:
blog_14:
blog_15:
blog_16:
